In [15]:
import numpy as np
from mnist import MNIST
from time import time
import pandas as pd
import os
from random import randint
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn import tree
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# load the MNIST digits dataset
mnist = datasets.load_digits()
X = pd.DataFrame(mnist.data)
print (X.shape)

(1797, 64)


In [16]:
# Split the data into training and test data
x_train, x_test, y_train, y_test = train_test_split(mnist.data, mnist.target, test_size=0.25, random_state=42)
print(len(x_train))
print(mnist.data.shape)

1347
(1797, 64)


In [17]:
clf = tree.DecisionTreeClassifier()
t0 = time()
clf = clf.fit(x_train, y_train)
print("training time:", round(time()-t0, 3), "s")
print(clf)
t1 = time()
predictions = clf.predict(x_test)
print("predicting time:", round(time()-t1, 3), "s")
print("Classification Report")
print(classification_report(y_test, predictions))
print("Overall Accuray")
print(accuracy_score(y_test, predictions)*100,'%')

training time: 0.017 s
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
predicting time: 0.001 s
Classification Report
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.89      0.84      0.86        37
           2       0.86      0.82      0.84        38
           3       0.79      0.80      0.80        46
           4       0.86      0.93      0.89        55
           5       0.91      0.83      0.87        59
           6       0.96      0.98      0.97        45
           7       0.85      0.95      0.90        41
           8       0.69      0.66      0.68        38
           9       0.88      0.94      

In [23]:
# load the iris datasets
load_iris_dataset = datasets.load_iris()
X_train, X_test, Y_train, Y_test = train_test_split(load_iris_dataset.data, load_iris_dataset.target, test_size=0.25
                                                    , random_state=1)
# fit a CART model to the data
model = tree.DecisionTreeClassifier()
t0 = time()
model.fit(X_train,Y_train)
print("training time:", round(time()-t0, 3), "s")
print(model)
t1 = time()
predicted = model.predict(X_test)
print("prediction time:", round(time()-t1, 3), "s")
# summarize the fit of the model
print(classification_report(Y_test, predicted))
print(accuracy_score(Y_test, predicted)*100)

training time: 0.0 s
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
prediction time: 0.0 s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

   micro avg       0.97      0.97      0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

97.36842105263158


In [24]:
load_wine_dataset = datasets.load_wine()
X_train, X_test, Y_train, Y_test = train_test_split(load_wine_dataset.data, load_wine_dataset.target, test_size=0.25
                                                    , random_state=0)
# fit a CART model to the data
model = tree.DecisionTreeClassifier()
t0 = time()
model.fit(X_train,Y_train)
print("training time:", round(time()-t0, 3), "s")
print(model)
t1 = time()
predicted = model.predict(X_test)
print("prediction time:", round(time()-t1, 3), "s")
# summarize the fit of the model
print(classification_report(Y_test, predicted))
print(accuracy_score(Y_test, predicted)*100)
print(confusion_matrix(Y_test, predicted))

training time: 0.001 s
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
prediction time: 0.001 s
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        16
           1       0.95      0.95      0.95        21
           2       0.89      1.00      0.94         8

   micro avg       0.96      0.96      0.96        45
   macro avg       0.95      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45

95.55555555555556
[[15  1  0]
 [ 0 20  1]
 [ 0  0  8]]


In [20]:
# load the iris datasets
dataset_breast_cancer = datasets.load_breast_cancer()
X_train, X_test, Y_train, Y_test = train_test_split(dataset_breast_cancer.data, dataset_breast_cancer.target, test_size=0.25
                                                    , random_state=0)
# fit a CART model to the data
model = tree.DecisionTreeClassifier()
t0 = time()
model.fit(X_train,Y_train)
print("training time:", round(time()-t0, 3), "s")
print(model)

t1 = time()
predicted = model.predict(X_test)
print("prediction time:", round(time()-t1, 3), "s")
# summarize the fit of the model
print(classification_report(Y_test, predicted))
print(accuracy_score(Y_test, predicted)*100)
print(confusion_matrix(Y_test, predicted))

training time: 0.005 s
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
prediction time: 0.0 s
              precision    recall  f1-score   support

           0       0.78      0.96      0.86        53
           1       0.97      0.84      0.90        90

   micro avg       0.89      0.89      0.89       143
   macro avg       0.88      0.90      0.88       143
weighted avg       0.90      0.89      0.89       143

88.81118881118881
[[51  2]
 [14 76]]
