In [1]:
import numpy as np
from mnist import MNIST
from time import time
import pandas as pd
import os
from random import randint
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:
# load the MNIST digits dataset
mnist = datasets.load_digits()

In [3]:
# Split the data into training and test data
x_train, x_test, y_train, y_test = train_test_split(mnist.data, mnist.target, test_size=0.25, random_state=42)
print(len(x_train))
print(mnist.data.shape)

1347
(1797, 64)


In [4]:
# Create the Multinomial Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
# Perform the predictions
t0 = time()
clf.fit(x_train,y_train)
print("training time:", round(time()-t0, 5), "s")
# Perform the predictions
t1 = time()
y_predicted = clf.predict(x_test)
print("predicting time:", round(time()-t1, 5), "s")
# Calculate the accuracy of the prediction
from sklearn.metrics import accuracy_score
print ("Accuracy = {} %".format(accuracy_score(y_test, y_predicted)*100))
# Cross validate the scores
from sklearn.metrics import classification_report
print ("Classification Report \n {}".format(classification_report(y_test, y_predicted, labels=range(0,10))))

training time: 0.02592 s
predicting time: 0.0 s
Accuracy = 91.55555555555556 %
Classification Report 
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        43
           1       0.90      0.73      0.81        37
           2       0.85      0.92      0.89        38
           3       1.00      0.89      0.94        46
           4       0.95      1.00      0.97        55
           5       0.96      0.86      0.91        59
           6       0.98      0.96      0.97        45
           7       0.93      1.00      0.96        41
           8       0.78      0.95      0.86        38
           9       0.80      0.85      0.83        48

   micro avg       0.92      0.92      0.92       450
   macro avg       0.92      0.91      0.91       450
weighted avg       0.92      0.92      0.92       450



In [9]:
from sklearn.naive_bayes import GaussianNB
# load the iris datasets
load_iris_dataset = datasets.load_iris()
x_train, x_test, y_train, y_test = train_test_split(load_iris_dataset.data, load_iris_dataset.target, test_size=0.25, random_state=42)
# fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(x_train, y_train)
print(model)
# make predictions
predicted = model.predict(x_test)
# summarize the fit of the model
print(classification_report(y_test, predicted))
print(accuracy_score(y_test, predicted)*100,'%')

GaussianNB(priors=None, var_smoothing=1e-09)
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

   micro avg       1.00      1.00      1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

100.0 %


In [10]:
from sklearn.naive_bayes import GaussianNB
load_wine_dataset = datasets.load_wine()
x_train, x_test, y_train, y_test = train_test_split(load_wine_dataset.data, load_wine_dataset.target, test_size=0.25, random_state=42)
# fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(x_train,y_train)
print(model)
# make predictions
expected = dataset.target
predicted = model.predict(x_test)
# summarize the fit of the model
print(classification_report(y_test, predicted))
print(accuracy_score(y_test, predicted)*100,'%')
print(confusion_matrix(y_test, predicted))

GaussianNB(priors=None, var_smoothing=1e-09)
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        12

   micro avg       1.00      1.00      1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

100.0 %
[[15  0  0]
 [ 0 18  0]
 [ 0  0 12]]


In [11]:
from sklearn.naive_bayes import GaussianNB
# load the iris datasets
load_breast_cancer_dataset = datasets.load_breast_cancer()
x_train, x_test, y_train, y_test = train_test_split(load_breast_cancer_dataset.data, load_breast_cancer_dataset.target, test_size=0.25, random_state=42)
# fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(x_train,y_train)
print(model)
# make predictions
predicted = model.predict(x_test)
# summarize the fit of the model
print(classification_report(y_test, predicted))
print(accuracy_score(y_test, predicted)*100,'%')
print(confusion_matrix(y_test, predicted))

GaussianNB(priors=None, var_smoothing=1e-09)
              precision    recall  f1-score   support

           0       0.94      0.94      0.94        54
           1       0.97      0.97      0.97        89

   micro avg       0.96      0.96      0.96       143
   macro avg       0.96      0.96      0.96       143
weighted avg       0.96      0.96      0.96       143

95.8041958041958 %
[[51  3]
 [ 3 86]]
