In [28]:
import numpy as np
from mnist import MNIST
from time import time
import pandas as pd
import os
from random import randint
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn.svm import SVC
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# load the MNIST digits dataset
mnist = datasets.load_digits()
X = pd.DataFrame(mnist.data)
print (X.shape)

(1797, 64)


In [29]:
# Split the data into training and test data
x_train, x_test, y_train, y_test = train_test_split(mnist.data, mnist.target, test_size=0.25, random_state=42)
print(len(x_train))
print(x_test)
print(len(y_test))
print(mnist.data.shape)

1347
[[ 0.  0.  0. ... 14.  5.  0.]
 [ 0.  0. 11. ...  1.  0.  0.]
 [ 0.  0.  8. ...  8.  0.  0.]
 ...
 [ 0.  1. 13. ... 12.  5.  0.]
 [ 0.  0.  0. ...  5.  0.  0.]
 [ 0.  6. 16. ...  0.  0.  0.]]
450
(1797, 64)


In [30]:
model = SVC(gamma='scale')
t0=time()
model.fit(x_train, y_train)
print("training time:", round(time()-t0, 3), "s")
print(model)

t1=time()
predictions = model.predict(x_test)
print("predict time:", round(time()-t1, 3), "s")

print("Classification Report")
print(classification_report(y_test, predictions))
print("Overall Accuray")
print(accuracy_score(y_test, predictions)*100,'%')

training time: 0.239 s
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
predict time: 0.031 s
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       1.00      1.00      1.00        37
           2       1.00      1.00      1.00        38
           3       1.00      0.96      0.98        46
           4       1.00      1.00      1.00        55
           5       0.95      1.00      0.98        59
           6       1.00      0.98      0.99        45
           7       0.98      0.98      0.98        41
           8       0.97      1.00      0.99        38
           9       0.98      0.96      0.97        48

   micro avg       0.99      0.99      0.99       450
   macro avg       0.99      0.99      0.99       450
wei

In [36]:
# load the iris datasets
load_iris_dataset = datasets.load_iris()
X_train, X_test, Y_train, Y_test = train_test_split(load_iris_dataset.data, load_iris_dataset.target, test_size=0.25
                                                    , random_state=0)
# fit a SVM model to the data
model = SVC()
t0 = time()
model.fit(X_train,Y_train)
print("training time:", round(time()-t0, 3), "s")
print(model)
t1 = time()
predicted = model.predict(X_test)
print("predict time:", round(time()-t1, 3), "s")
# summarize the fit of the model
print(classification_report(Y_test, predicted))
print(accuracy_score(Y_test, predicted)*100,'%')

training time: 0.001 s
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
predict time: 0.0 s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

   micro avg       0.97      0.97      0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

97.36842105263158 %


In [42]:

load_wine_dataset = datasets.load_wine()
X_train, X_test, Y_train, Y_test = train_test_split(load_wine_dataset.data, load_wine_dataset.target, test_size=0.25
                                                    , random_state=0)
# fit a SVM model to the data
model = SVC(gamma="scale")
t0 = time()
model.fit(X_train,Y_train)
print("training time:", round(time()-t0, 3), "s")
# make predictions
expected = dataset.target
t1 = time()
predicted = model.predict(X_test)
print("predict time:", round(time()-t1, 3), "s")
# summarize the fit of the model
print("Classification Report")
print(classification_report(Y_test, predicted))
print("Accuracy")
print(accuracy_score(Y_test, predicted)*100,'%')
print("Confusion Matrix")
print(confusion_matrix(Y_test, predicted))
print(X_test.shape)

training time: 0.001 s
predict time: 0.0 s
Classification Report
              precision    recall  f1-score   support

           0       0.82      0.88      0.85        16
           1       0.79      0.71      0.75        21
           2       0.22      0.25      0.24         8

   micro avg       0.69      0.69      0.69        45
   macro avg       0.61      0.61      0.61        45
weighted avg       0.70      0.69      0.69        45

Accuracy
68.88888888888889 %
Confusion Matrix
[[14  1  1]
 [ 0 15  6]
 [ 3  3  2]]
(45, 13)


In [39]:
# load the iris datasets
dataset_breast_cancer = datasets.load_breast_cancer()
X_train, X_test, Y_train, Y_test = train_test_split(dataset_breast_cancer.data, dataset_breast_cancer.target, test_size=0.25
                                                    , random_state=0)
# fit a SVM model to the data
model = SVC(gamma="scale")
t0 = time()
model.fit(X_train,Y_train)
print("training time:", round(time()-t0, 3), "s")
print(model)
# make predictions
t1 = time()
predicted = model.predict(X_test)
print("predict time:", round(time()-t1, 3), "s")
# summarize the fit of the model
print(classification_report(Y_test, predicted))
print(accuracy_score(Y_test, predicted)*100,'%')
print(confusion_matrix(Y_test, predicted))

training time: 0.006 s
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
predict time: 0.002 s
              precision    recall  f1-score   support

           0       0.94      0.92      0.93        53
           1       0.96      0.97      0.96        90

   micro avg       0.95      0.95      0.95       143
   macro avg       0.95      0.95      0.95       143
weighted avg       0.95      0.95      0.95       143

95.1048951048951 %
[[49  4]
 [ 3 87]]
